export const plans = [
  {
    name: 'STARTER',
    price: '0',
    yearlyPrice: '0',
    period: 'per user / per month',
    features: ['Unlimited Projects', 'Up to 2 Team Members', '48-hour support response time'],
    description: 'Perfect for individuals and small projects',
    buttonText: 'Start Free Trial',
    href: '/register',
    isPopular: false,
  },
  {
    name: 'PROFESSIONAL',
    price: '10',
    yearlyPrice: '100',
    period: 'per user / month',
    features: [
      'Everything in Starter',
      'First two members for Free',
      '24-hour support response time',
      'Team collaboration',
      '3rd Party integrations',
      'API integrations',
    ],
    description: 'Ideal for growing teams and businesses',
    buttonText: 'Get Started',
    href: '/register?plan=pro',
    isPopular: true,
  },
  {
    name: 'ENTERPRISE',
    period: '',
    features: [
      'Everything in Professional',
      'SSO Authentication',
      'Analytics',
      'SLA agreement',
      'Custom contracts',
      '8-hour support response time',
    ],
    description: 'For large organizations with specific needs',
    buttonText: 'Contact Sales',
    href: '/contact',
    isPopular: false,
  },
];
