export const plans = [
  {
    name: 'STARTER',
    price: '0',
    yearlyPrice: '0',
    period: 'per user / per month',
    features: ['Unlimited Projects', 'Up to 2 Team Members', '48-hour support response time'],
    description: 'Perfect for individuals and small projects',
    buttonText: 'Start Free Trial',
    href: '/sign-up',
    isPopular: false,
  },
  {
    name: 'PROFESSIONAL',
    price: '10',
    yearlyPrice: '100',
    period: 'per user / month',
    features: [
      'Everything in Starter',
      'Up to 15 Team Members',
      '24-hour support response time',
      'Priority support',
      'Team collaboration',
      'Custom integrations',
      'API integrations',
    ],
    description: 'Ideal for growing teams and businesses',
    buttonText: 'Get Started',
    href: '/sign-up',
    isPopular: true,
  },
  {
    name: 'ENTERPRISE',
    price: '50',
    yearlyPrice: '500',
    period: 'per month',
    features: [
      'Everything in Professional',
      'Custom solutions',
      'Dedicated account manager',
      '1-hour support response time',
      'SSO Authentication',
      'Analytics',
      'Custom Servers Support',
      'Custom contracts',
      'SLA agreement',
    ],
    description: 'For large organizations with specific needs',
    buttonText: 'Contact Sales',
    href: '/contact',
    isPopular: false,
  },
];
