import {
  ImageSquare,
  House,
  User,
  Phone,
  Calendar,
  Clock,
  Heart,
  Star,
  Video,
  File,
  Folder,
  Download,
  Upload,
  Share,
  Link,
  Globe,
  Chat,
  Bell,
  Camera,
  Coffee,
  Desktop,
  GameController,
  Lightning,
  Moon,
  Sun,
  Cloud,
  Airplane,
  Car,
  Train,
  Bicycle,
  ShoppingCart,
  Bank,
  CurrencyDollar,
  CreditCard,
  Trophy,
  Crown,
  Diamond,
  Fire,
  Leaf,
  Palette,
  Pi,
  Axe,
  Bed,
} from '@phosphor-icons/react';

export const colors = [
  { color: '#125CBD', accentColor: '#071233' },
  { color: '#F94144', accentColor: '#330C0D' },
  { color: '#F3722C', accentColor: '#331309' },
  { color: '#F9C74F', accentColor: '#33270A' },
  { color: '#90BE6D', accentColor: '#142610' },
  { color: '#43AA8B', accentColor: '#0D1E1A' },
  { color: '#577590', accentColor: '#0C141B' },
  { color: '#F9844A', accentColor: '#331710' },
  { color: '#4D908E', accentColor: '#0C1A1A' },
  { color: '#F8961E', accentColor: '#331C0A' },
] as const;

export const icons = [
  { name: 'Image', component: ImageSquare },
  { name: 'House', component: House },
  { name: 'User', component: User },
  { name: 'Phone', component: Phone },
  { name: 'Calendar', component: Calendar },
  { name: 'Clock', component: Clock },
  { name: 'Heart', component: Heart },
  { name: 'Star', component: Star },
  { name: 'Video', component: Video },
  { name: 'File', component: File },
  { name: 'Folder', component: Folder },
  { name: 'Download', component: Download },
  { name: 'Upload', component: Upload },
  { name: 'Share', component: Share },
  { name: 'Link', component: Link },
  { name: 'Globe', component: Globe },
  { name: 'Chat', component: Chat },
  { name: 'Bell', component: Bell },
  { name: 'Camera', component: Camera },
  { name: 'Coffee', component: Coffee },
  { name: 'Desktop', component: Desktop },
  { name: 'Game', component: GameController },
  { name: 'Lightning', component: Lightning },
  { name: 'Moon', component: Moon },
  { name: 'Sun', component: Sun },
  { name: 'Cloud', component: Cloud },
  { name: 'Airplane', component: Airplane },
  { name: 'Car', component: Car },
  { name: 'Train', component: Train },
  { name: 'Bicycle', component: Bicycle },
  { name: 'Cart', component: ShoppingCart },
  { name: 'Bank', component: Bank },
  { name: 'Dollar', component: CurrencyDollar },
  { name: 'Card', component: CreditCard },
  { name: 'Trophy', component: Trophy },
  { name: 'Crown', component: Crown },
  { name: 'Diamond', component: Diamond },
  { name: 'Fire', component: Fire },
  { name: 'Leaf', component: Leaf },
  { name: 'Palette', component: Palette },
  { name: 'Pi', component: Pi },
  { name: 'Axe', component: Axe },
  { name: 'Bed', component: Bed },
] as const;
