name: Build And Upload Chrome Extension Zip Via Artifact

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/extension/CHANGELOG.md'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - run: pnpm install --frozen-lockfile --prefer-offline

      - run: pnpm build:chrome

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*
